---
- hosts: localhost
  remote_user: root
  tasks:
    - name: install gems
      gem: name={{item}} state=latest user_install=no
      with_items:
        - awesome_print
        - aws-sdk-v1
        - bundler
        - pry
